### PR TITLE
Add retunred->returned.

### PR DESCRIPTION
**Pull request by shurcooL**
Originally encountered in https://github.com/golang/gddo/blob/eb44e37ce297392abc76d1ac1ca8343a77f43662/database/database_test.go#L124. Though it was a misspelling inside a Go string, not a comment, so this tool wouldn't have fixed that particular instance. But maybe it'll help elsewhere?

Since #4 is not resolved, there's a chance I did something wrong. It's my first time adding a missing word here, so I'm not familiar with the process. Please review.

### CODE REVIEW

**Comment by shurcooL** [comment]
Hi, any feedback on this PR?

**Comment by client9** [comment]
hi 
thanks

I'm still working on best system here, and working on removing the FP issue.
  I'll merge this in manually.

**Comment by shurcooL** [comment]
> I'll merge this in manually.

All right, thanks.

What is FP issue?

**Comment by client9** [comment]
not related to you, but with about 600 other ones :-)

**Comment by shurcooL** [comment]
> What is FP issue?

Ah, figured it out now, FP stands for "false positive".

**Pull request closed without merging**
